// Deep dossier translations — batch 2: ja, zh, zhTw, ko.
// Same structure as dossier-i18n.js. Composed into SEL2[lang][gameId] and merged at runtime.
// Proper nouns kept in English (Black Ops, Modern Warfare, Warzone, Prestige, Nuketown, Blackout, Omnimovement,
// RICOCHET, Battle Pass, Call of Duty HQ, Zombies, MWZ, DMZ, Verdansk, Gunsmith, Pick 10, Carry-Forward, etc.).

const META = { bo1:['finalTitle','legacy'], bo2:['finalTitle','legacy'], bo3:['finalTitle','legacy'], bo4:['finalTitle','legacy'], mw2019:['finalSeasonal','legacy'], cw:['finalSeasonal','legacy'], mw2:['finalSeasonal','legacy'], mw3:['finalSeasonal','legacy'], bo6:['currentSeason','live'], bo7:['launchSeason','live'], mw4:['unannounced','awaiting'] };
const STDMAX = { bo2:['10','Master'], bo3:['10','1000'], bo4:['10','Master'], bo6:['10','1000'], bo7:['10','1000'] };
const TN = { bo1:['Prestige 1','Prestige 10','Prestige 15','Prestige Shop'], mw2019:['Rank 55','Season Level 1','Officer Rank','Officer 155'], cw:['Prestige 1','Prestige 3','Prestige Master','Master 1000'], mw2:['Rank 55','Prestige 1–5','Season Level 250','Battle Pass'], mw3:['Prestige 1','Prestige 10','Prestige Master','Master 1000'], mw4:['TBA'] };
const CUSTOM_ROAD = ['bo6','bo7','mw4'];

function build(L) {
  const out = {};
  Object.keys(META).forEach(gid => {
    const g = L.g[gid];
    const [pvk, pdk] = META[gid];
    let tiers;
    if (STDMAX[gid]) {
      const [max, master] = STDMAX[gid];
      const nm = ['Prestige 1', 'Prestige 5', 'Prestige ' + max, 'Master ' + master];
      tiers = nm.map((name, i) => ({ name, req: L.stdReq[i], reward: L.stdReward[i] }));
    } else {
      tiers = TN[gid].map((name, i) => ({ name, req: g.tiers[i].req, reward: g.tiers[i].reward }));
    }
    const roadmap = CUSTOM_ROAD.includes(gid) ? g.roadmap : [{ q: L.statusQ, item: L.legacyItem }];
    out[gid] = { patchVersion: L.pv[pvk], patchDate: L.pd[pdk], highlights: g.highlights, matchmaking: g.matchmaking, tiers, rewardSupport: g.rs, roadmap };
  });
  return out;
}

const JA = {
  pv: { finalTitle:'最終タイトルアップデート', finalSeasonal:'最終シーズンアップデート', currentSeason:'現行シーズン', launchSeason:'ローンチシーズン', unannounced:'未発表' },
  pd: { legacy:'レガシービルド', live:'ライブサービス · シーズンごとに更新', awaiting:'公式発表待ち' },
  stdReq: ['最大ランクでリセット', '5回のリセット', '最終プレステージ', 'プレステージ後の周回'],
  stdReward: ['プレステージエンブレム、コーリングカード、新たなアンロック進行', 'リセットをまたいで武器/パークを保持できる永久アンロックトークン', 'ボーナスクラススロット、プレステージアイコン、Prestige Shopへのアクセス', 'Dark Ops / Master コーリングカードとレガシーエンブレム'],
  statusQ:'ステータス', legacyItem:'レガシータイトル — 今後のコンテンツ更新の予定はありません。オンラインプレイ用にサーバーは稼働を続けます。',
  g: {
    bo1:{ highlights:['コアMP武器と装備の最終バランス調整。','ウェイジャーマッチ向けにContractsとCOD Pointsの経済を確定。','オンラインプレイ向けの専用サーバーとアンチチートの保守。'], matchmaking:'マッチ間でロビーが継続する接続優先のロビー — SBMM以前の時代。ホスト/専用のハイブリッドで、プレイヤーは試合をまたいで一緒のまま。', tiers:[{req:'ランク50でリセット',reward:'プレステージエンブレム + Prestige Tokenによる永久アンロック1つ'},{req:'10回のリセット',reward:'プレステージごとにCreate-a-Classスロットを追加'},{req:'最終プレステージ',reward:'最大アンロックトークン、限定エンブレム、Fallコーリングカード'},{req:'任意のプレステージ',reward:'全アンロックの払い戻し / 永久アンロックの選択'}], rs:['独立した進行 — タイトル間の引き継ぎなし。','プレステージのアンロックとCOD PointsはBlack Ops (2010)内に留まります。'] },
    bo2:{ highlights:['全クラスでPick 10ロードアウトのバランスを確定。','League PlayディビジョンとランクシーズンをＬ終了。','スコアストリーク調整と最終的な武器調整。'], matchmaking:'接続ベースのマッチメイキングと、任意のスキル別League Playディビジョン（Bronze → Master）。カジュアルプレイリストは接続を優先します。', rs:['独立した進行 — アンロックはBlack Ops IIに限定。','Prestige Masterはこのタイトル内で全アイテムを恒久的にアンロック。'] },
    bo3:{ highlights:['スペシャリスト能力と武器のバランスを確定。','Black Market / サプライドロップのコスメを全てローテーションで解放。','Zombies Chroniclesマップパックの統合と修正。'], matchmaking:'ArenaのランクシーズンありのスキルＬ影響型マッチメイキング。標準プレイリストは接続と直近の戦績を考慮します。', rs:['独立した進行 — HQ/Warzone連携なし（Warzone以前）。','Master Prestige（1000まで）でプレステージ限定コーリングカードとアイコンを付与。'] },
    bo4:{ highlights:['スペシャリストと手動回復のバランスを確定。','Blackoutバトルロイヤルのマップと車両調整を終了。','Black Market Contrabandの段階報酬を全て設定。'], matchmaking:'MPとBlackout全体でのスキルベースマッチメイキング。直近の戦績と接続を考慮し、ロビーは各マッチ後に解散します。', rs:['独立した進行 — Blackout、MP、Zombiesが1つのアカウントレベルを共有。','Contraband/Black Marketの段階でシーズンごとにコスメを解放。'] },
    mw2019:{ highlights:['全プラットフォームでGunsmithと武器のバランスを確定。','Warzone（Verdansk）統合とロードアウト調整を終了。','シーズンのオフィサーランク報酬を全てローテーション。'], matchmaking:'マッチごとにスキル、接続、直近の結果を組み合わせるスキルベースマッチメイキング。ロビーは各試合で解散（継続なし）。', tiers:[{req:'基本上限',reward:'プレステージとシーズンのオフィサー進行を解放'},{req:'55以降、シーズンごと',reward:'Battle Passの段階、武器、Warzoneコスメ'},{req:'シーズンの周回',reward:'シーズン限定のエンブレム、コーリングカード、武器チャーム'},{req:'シーズン最大',reward:'最高のシーズン報酬 + プレステージアイコン'}], rs:['オリジナルWarzone（Verdansk時代）と進行を共有。','アンロック/設計図はオリジナルWarzoneで使用可能。以降のHQタイトルとは非連携。'] },
    cw:{ highlights:['Warzoneとのゲーム間武器バランスを確定。','シーズンのPrestige Master（レベル1000まで）報酬を全てローテーション。','Zombies Outbreakとラウンド制の調整を終了。'], matchmaking:'スキル、接続、直近の戦績を考慮するスキルベースマッチメイキング。ロビーは各マッチで解散。ランク方式のシーズンプレステージリセットあり。', tiers:[{req:'55でリセット',reward:'プレステージエンブレム + シーズン進行のリセット'},{req:'シーズン制',reward:'シーズン限定アイコン。シーズンのプレステージレベルを引き継ぐ'},{req:'全プレステージ後',reward:'Masterレベル1〜1000へのアクセス'},{req:'シーズンの周回',reward:'Prestige Masterコーリングカードと恒久アイコン'}], rs:['統合上限を介してWarzone（2020〜2021時代）とレベル、Battle Pass、武器を共有。','ここで獲得した設計図とOperatorはWarzoneで使用可能。'] },
    mw2:{ highlights:['武器プラットフォーム/レシーバーの進行を確定。','Warzone 2.0とDMZの統合調整を終了。','シーズンのプレステージランク（シーズンごとに250まで）を全てローテーション。'], matchmaking:'MPとWarzone全体で、スキル、接続、直近の戦績を組み合わせるスキルベースマッチメイキング。ロビーは各マッチで解散。', tiers:[{req:'基本上限',reward:'シーズンのプレステージ進行を解放'},{req:'シーズンごと',reward:'レベル50/100/150/200/250でのシーズンプレステージアイコン'},{req:'シーズン最大',reward:'シーズン限定の武器設計図とエンブレム'},{req:'シーズンごと',reward:'HQ経由の武器、Operator、Warzoneコスメ'}], rs:['Call of Duty HQの基盤 — Warzone 2.0と進行を共有。','武器プラットフォームとレシーバーを共有。コンテンツはMWIIIに引き継ぎ。'] },
    mw3:{ highlights:['MWIIの武器、Operator、バンドルのCarry-Forwardを確定。','Modern Warfare Zombies（MWZ）の段階とミッションを終了。','シーズンのPrestige Master（1000まで）報酬を全てローテーション。'], matchmaking:'MP、Warzone、MWZ全体で、スキル、接続、直近の戦績を組み合わせるスキルベースマッチメイキング。ロビーは各マッチで解散。', tiers:[{req:'55でリセット',reward:'プレステージエンブレム + シーズンリセット'},{req:'シーズンごと',reward:'50レベルごとのシーズンプレステージアイコン'},{req:'プレステージ10以降',reward:'Masterレベル1〜1000'},{req:'シーズンの周回',reward:'Prestige Masterコーリングカードとアイコン'}], rs:['Carry-Forward：MWIIの全武器、Operator、設計図を引き継ぎ。','HQ経由でWarzoneおよびMWZと進行とBattle Passを統合。'] },
    bo6:{ highlights:['Omnimovement調整：スプリント・スライド・ダイブのバランスとリコイル調整。','シーズンの武器追加とメタバランス調整。','Zombiesマップ、Easter egg、Prestige Master報酬のローテーション。','Warzone統合：インベントリ共有とBattle Passの同期。'], matchmaking:'スキルベースマッチメイキングは各マッチでスキル、接続、直近の戦績を組み合わせ、ロビーは各試合後に解散。Ranked PlayはSRベースの可視スキルディビジョンラダーを追加。', rs:['Call of Duty HQを通じてWarzoneと進行を統合。','Carry Forward：対象のMWII/MWIIIコンテンツはWarzoneで使用可能（BO6のMPでは不可）。','Battle PassとPrestigeをBO6のMP、Zombies、Warzoneで共有。'], roadmap:[{q:'シーズン中',item:'継続中：中／大型シーズン更新ごとに新しいMPマップ、武器、Zombiesコンテンツ。'},{q:'RANKED PLAY',item:'スキルディビジョン、SR、ランク限定報酬のある競技シーズン。'},{q:'WARZONE',item:'継続的な統合と、シーズンに連動したResurgence・BRマップのローテーション。'}] },
    bo7:{ highlights:['ローンチのマルチプレイヤー、Zombies、キャンペーンが初日バランス調整とともに稼働。','洗練されたOmnimovementと刷新されたロードアウト/パークシステム。','マップ、武器、イベントのシーズンロードマップが進行中。','Call of Duty HQとWarzoneの進行を完全統合。'], matchmaking:'スキルベースマッチメイキングは各マッチでスキル、接続、直近の戦績を組み合わせ、ロビーは各試合後に解散。Ranked PlayはSRディビジョンとシーズン報酬とともに復帰。', rs:['Call of Duty HQの統合進行をWarzoneとともに継続。','PrestigeとBattle PassをMP、Zombies、Warzoneで共有。','一部のBO6時代のコンテンツが共有エコシステムに引き継がれます。'], roadmap:[{q:'ローンチ',item:'シーズン1稼働：ローンチマップ、武器、Ranked Playのプレシーズン。'},{q:'シーズン中盤',item:'Reloadedドロップでマップ、武器、イベント、Zombiesコンテンツを追加。'},{q:'継続中',item:'継続的なWarzone統合とシーズンごとのBattle Passの周期。'}] },
    mw4:{ highlights:['公式パッチノートはまだなし — このタイトルは未確定です。','Call of Duty HQの統合進行を継続する見込み。','プレースホルダーセクション — Activisionが詳細を発表次第、記載します。'], matchmaking:'近年のタイトルに沿ったスキルベースマッチメイキング（スキル＋接続＋直近の戦績、ロビーは各マッチで解散）を使用する見込み。未確定。', tiers:[{req:'発表待ち',reward:'ランクとプレステージの構成は未発表。'}], rs:['Call of Duty HQ経由でWarzoneと連携する見込み。','Carry-Forward対応は発表まで未確定。'], roadmap:[{q:'未確定',item:'公式発表はありません。これはコミュニティが待望する次回作のプレースホルダーです。'}] },
  },
};

const ZH = {
  pv: { finalTitle:'最终标题更新', finalSeasonal:'最终赛季更新', currentSeason:'当前赛季', launchSeason:'发行赛季', unannounced:'未公布' },
  pd: { legacy:'旧版构建', live:'实时服务 · 按赛季更新', awaiting:'等待官方公布' },
  stdReq: ['满级时重置', '五次重置', '最终威望', '威望后刷取'],
  stdReward: ['威望徽章、名片及全新解锁进度', '可跨重置保留一把武器/一个特长的永久解锁令牌', '额外职业槽、威望图标及 Prestige Shop 权限', 'Dark Ops / Master 名片及旧版徽章'],
  statusQ:'状态', legacyItem:'旧版作品——无进一步内容更新计划。服务器仍保持在线以供联机游玩。',
  g: {
    bo1:{ highlights:['对核心多人武器与装备进行最终平衡调整。','为对赌对局最终确定 Contracts 与 COD Points 经济。','为联机游玩维护专用服务器与反作弊。'], matchmaking:'以连接为先的房间，对局之间保留房间——SBMM 之前的时代。主机/专用混合；玩家在多局之间保持在一起。', tiers:[{req:'在 50 级重置',reward:'威望徽章 + 通过 Prestige Token 获得一次永久解锁'},{req:'十次重置',reward:'每次威望额外一个 Create-a-Class 槽位'},{req:'最终威望',reward:'满级解锁令牌、专属徽章及 Fall 名片'},{req:'任意威望',reward:'退还所有解锁 / 选择永久解锁'}], rs:['独立进度——无跨作品继承。','威望解锁与 COD Points 仅保留在 Black Ops (2010) 内。'] },
    bo2:{ highlights:['在所有职业上最终确定 Pick 10 配装平衡。','League Play 分段与排位赛季收官。','连杀调整与最终武器改动。'], matchmaking:'基于连接的匹配，附带可选的按技术分级的 League Play 分段（青铜 → 大师）。休闲列表优先考虑连接。', rs:['独立进度——解锁仅限 Black Ops II。','Prestige Master 在本作内永久解锁所有物品。'] },
    bo3:{ highlights:['最终确定专家能力与武器平衡。','Black Market / 补给掉落饰品全部轮换解锁。','Zombies Chronicles 地图包整合与修复。'], matchmaking:'带 Arena 排位赛季的技术影响型匹配。标准列表权衡连接与近期表现。', rs:['独立进度——无 HQ/Warzone 关联（Warzone 之前）。','Master Prestige（至 1000）授予威望专属名片与图标。'] },
    bo4:{ highlights:['最终确定专家与手动治疗平衡。','Blackout 大逃杀地图与载具调整收官。','Black Market Contraband 阶级奖励全部铺设完成。'], matchmaking:'在 MP 与 Blackout 中的技术匹配，权衡近期表现与连接；房间在每局后解散。', rs:['独立进度——Blackout、MP 与 Zombies 共享一个账户等级。','Contraband/Black Market 阶级按赛季解锁饰品。'] },
    mw2019:{ highlights:['在所有平台最终确定 Gunsmith 与武器平衡。','Warzone（Verdansk）整合与配装调整收官。','赛季军官军衔奖励全部轮换。'], matchmaking:'融合技术、连接与每局近期结果的技术匹配。房间在每局解散（无保留）。', tiers:[{req:'基础上限',reward:'解锁威望与赛季军官进度'},{req:'55 级后，按赛季',reward:'Battle Pass 阶级、武器及 Warzone 饰品'},{req:'赛季刷取',reward:'赛季专属徽章、名片及武器挂件'},{req:'赛季上限',reward:'顶级赛季奖励 + 威望图标'}], rs:['与初代 Warzone（Verdansk 时代）共享进度。','解锁/蓝图可在初代 Warzone 使用；不与后续 HQ 作品关联。'] },
    cw:{ highlights:['与 Warzone 的跨游戏武器平衡收官。','赛季 Prestige Master（至 1000 级）奖励全部轮换。','Zombies Outbreak 与回合制调整收官。'], matchmaking:'权衡技术、连接与近期表现的技术匹配；房间在每局解散。带排位式赛季威望重置。', tiers:[{req:'在 55 级重置',reward:'威望徽章 + 赛季进度重置'},{req:'赛季制',reward:'赛季专属图标；保留赛季威望等级'},{req:'越过所有威望后',reward:'解锁 Master 等级 1–1000'},{req:'赛季刷取',reward:'Prestige Master 名片与永久图标'}], rs:['通过统一上限与 Warzone（2020–2021 时代）共享等级、Battle Pass 与武器。','此处获得的蓝图与 Operator 可在 Warzone 使用。'] },
    mw2:{ highlights:['最终确定武器平台/机匣进度。','Warzone 2.0 与 DMZ 整合调整收官。','赛季威望军衔（每赛季至 250）全部轮换。'], matchmaking:'在 MP 与 Warzone 中融合技术、连接与近期表现的技术匹配；房间在每局解散。', tiers:[{req:'基础上限',reward:'解锁赛季威望进度'},{req:'按赛季',reward:'在 50/100/150/200/250 级的赛季威望图标'},{req:'赛季上限',reward:'赛季专属武器蓝图与徽章'},{req:'按赛季',reward:'通过 HQ 获得武器、Operator 及 Warzone 饰品'}], rs:['Call of Duty HQ 的基础——与 Warzone 2.0 共享进度。','武器平台与机匣共享；内容延续至 MWIII。'] },
    mw3:{ highlights:['最终确定 MWII 武器、Operator 与捆绑包的 Carry-Forward。','Modern Warfare Zombies（MWZ）阶级与任务收官。','赛季 Prestige Master（至 1000）奖励全部轮换。'], matchmaking:'在 MP、Warzone 与 MWZ 中融合技术、连接与近期表现的技术匹配；房间在每局解散。', tiers:[{req:'在 55 级重置',reward:'威望徽章 + 赛季重置'},{req:'按赛季',reward:'每 50 级的赛季威望图标'},{req:'越过威望 10 后',reward:'Master 等级 1–1000'},{req:'赛季刷取',reward:'Prestige Master 名片与图标'}], rs:['Carry-Forward：所有 MWII 武器、Operator 与蓝图均转入。','通过 HQ 与 Warzone 及 MWZ 统一进度与 Battle Pass。'] },
    bo6:{ highlights:['Omnimovement 调整：冲刺-滑铲-俯冲平衡与后坐力调整。','赛季武器新增与 meta 平衡调整。','Zombies 地图、Easter egg 与 Prestige Master 奖励轮换。','Warzone 整合：共享库存与 Battle Pass 同步。'], matchmaking:'技术匹配每局融合技术、连接与近期表现；房间在每局后解散。Ranked Play 增加可见的基于 SR 的技术分段阶梯。', rs:['通过 Call of Duty HQ 与 Warzone 统一进度。','Carry Forward：符合条件的 MWII/MWIII 内容仍可在 Warzone 使用（BO6 MP 除外）。','Battle Pass 与威望在 BO6 MP、Zombies 与 Warzone 间共享。'], roadmap:[{q:'赛季进行中',item:'持续进行：每次中/大型赛季更新带来新的 MP 地图、武器与 Zombies 内容。'},{q:'RANKED PLAY',item:'带技术分段、SR 与军衔锁定奖励的竞技赛季。'},{q:'WARZONE',item:'持续整合，Resurgence 与 BR 地图轮换与赛季挂钩。'}] },
    bo7:{ highlights:['发行多人、Zombies 与战役实时上线，附带首日平衡调整。','精炼的 Omnimovement 与全新的配装/特长系统。','地图、武器与活动的赛季路线图进行中。','完整整合 Call of Duty HQ 与 Warzone 进度。'], matchmaking:'技术匹配每局融合技术、连接与近期表现；房间在每局后解散。Ranked Play 携 SR 分段与赛季奖励回归。', rs:['与 Warzone 一同延续统一的 Call of Duty HQ 进度。','威望与 Battle Pass 在 MP、Zombies 与 Warzone 间共享。','部分 BO6 时代内容转入共享生态。'], roadmap:[{q:'发行',item:'第 1 赛季上线：发行地图、武器与 Ranked Play 季前赛。'},{q:'赛季中期',item:'Reloaded 更新新增地图、武器、活动与 Zombies 内容。'},{q:'持续进行',item:'持续的 Warzone 整合与赛季 Battle Pass 节奏。'}] },
    mw4:{ highlights:['尚无官方补丁说明——本作未确认。','预计将延续 Call of Duty HQ 统一进度。','占位板块——待 Activision 公布详情后填写。'], matchmaking:'预计采用与近期作品一致的技术匹配（技术 + 连接 + 近期表现，房间每局解散）。未确认。', tiers:[{req:'等待公布',reward:'军衔与威望结构尚未公布。'}], rs:['预计通过 Call of Duty HQ 与 Warzone 关联。','Carry-Forward 支持在公布前未确认。'], roadmap:[{q:'未确认',item:'无官方公告。这是社区期待的下一作的占位内容。'}] },
  },
};

const ZHTW = {
  pv: { finalTitle:'最終標題更新', finalSeasonal:'最終賽季更新', currentSeason:'目前賽季', launchSeason:'發行賽季', unannounced:'未公布' },
  pd: { legacy:'舊版建置', live:'即時服務 · 依賽季更新', awaiting:'等待官方公布' },
  stdReq: ['滿級時重置', '五次重置', '最終威望', '威望後刷取'],
  stdReward: ['威望徽章、名片及全新解鎖進度', '可跨重置保留一把武器/一個專長的永久解鎖令牌', '額外職業槽、威望圖示及 Prestige Shop 權限', 'Dark Ops / Master 名片及舊版徽章'],
  statusQ:'狀態', legacyItem:'舊版作品——無進一步內容更新計畫。伺服器仍保持在線以供連線遊玩。',
  g: {
    bo1:{ highlights:['對核心多人武器與裝備進行最終平衡調整。','為對賭對局最終確定 Contracts 與 COD Points 經濟。','為連線遊玩維護專用伺服器與反作弊。'], matchmaking:'以連線為先的房間，對局之間保留房間——SBMM 之前的時代。主機/專用混合；玩家在多局之間保持在一起。', tiers:[{req:'在 50 級重置',reward:'威望徽章 + 透過 Prestige Token 獲得一次永久解鎖'},{req:'十次重置',reward:'每次威望額外一個 Create-a-Class 槽位'},{req:'最終威望',reward:'滿級解鎖令牌、專屬徽章及 Fall 名片'},{req:'任意威望',reward:'退還所有解鎖 / 選擇永久解鎖'}], rs:['獨立進度——無跨作品繼承。','威望解鎖與 COD Points 僅保留在 Black Ops (2010) 內。'] },
    bo2:{ highlights:['在所有職業上最終確定 Pick 10 配裝平衡。','League Play 分段與排位賽季收官。','連殺調整與最終武器改動。'], matchmaking:'基於連線的配對，附帶可選的依技術分級的 League Play 分段（青銅 → 大師）。休閒列表優先考慮連線。', rs:['獨立進度——解鎖僅限 Black Ops II。','Prestige Master 在本作內永久解鎖所有物品。'] },
    bo3:{ highlights:['最終確定專家能力與武器平衡。','Black Market / 補給掉落飾品全部輪換解鎖。','Zombies Chronicles 地圖包整合與修正。'], matchmaking:'帶 Arena 排位賽季的技術影響型配對。標準列表權衡連線與近期表現。', rs:['獨立進度——無 HQ/Warzone 關聯（Warzone 之前）。','Master Prestige（至 1000）授予威望專屬名片與圖示。'] },
    bo4:{ highlights:['最終確定專家與手動治療平衡。','Blackout 大逃殺地圖與載具調整收官。','Black Market Contraband 階級獎勵全部鋪設完成。'], matchmaking:'在 MP 與 Blackout 中的技術配對，權衡近期表現與連線；房間在每局後解散。', rs:['獨立進度——Blackout、MP 與 Zombies 共享一個帳戶等級。','Contraband/Black Market 階級依賽季解鎖飾品。'] },
    mw2019:{ highlights:['在所有平台最終確定 Gunsmith 與武器平衡。','Warzone（Verdansk）整合與配裝調整收官。','賽季軍官軍階獎勵全部輪換。'], matchmaking:'融合技術、連線與每局近期結果的技術配對。房間在每局解散（無保留）。', tiers:[{req:'基礎上限',reward:'解鎖威望與賽季軍官進度'},{req:'55 級後，依賽季',reward:'Battle Pass 階級、武器及 Warzone 飾品'},{req:'賽季刷取',reward:'賽季專屬徽章、名片及武器吊飾'},{req:'賽季上限',reward:'頂級賽季獎勵 + 威望圖示'}], rs:['與初代 Warzone（Verdansk 時代）共享進度。','解鎖/藍圖可在初代 Warzone 使用；不與後續 HQ 作品關聯。'] },
    cw:{ highlights:['與 Warzone 的跨遊戲武器平衡收官。','賽季 Prestige Master（至 1000 級）獎勵全部輪換。','Zombies Outbreak 與回合制調整收官。'], matchmaking:'權衡技術、連線與近期表現的技術配對；房間在每局解散。帶排位式賽季威望重置。', tiers:[{req:'在 55 級重置',reward:'威望徽章 + 賽季進度重置'},{req:'賽季制',reward:'賽季專屬圖示；保留賽季威望等級'},{req:'越過所有威望後',reward:'解鎖 Master 等級 1–1000'},{req:'賽季刷取',reward:'Prestige Master 名片與永久圖示'}], rs:['透過統一上限與 Warzone（2020–2021 時代）共享等級、Battle Pass 與武器。','此處獲得的藍圖與 Operator 可在 Warzone 使用。'] },
    mw2:{ highlights:['最終確定武器平台/槍機進度。','Warzone 2.0 與 DMZ 整合調整收官。','賽季威望軍階（每賽季至 250）全部輪換。'], matchmaking:'在 MP 與 Warzone 中融合技術、連線與近期表現的技術配對；房間在每局解散。', tiers:[{req:'基礎上限',reward:'解鎖賽季威望進度'},{req:'依賽季',reward:'在 50/100/150/200/250 級的賽季威望圖示'},{req:'賽季上限',reward:'賽季專屬武器藍圖與徽章'},{req:'依賽季',reward:'透過 HQ 獲得武器、Operator 及 Warzone 飾品'}], rs:['Call of Duty HQ 的基礎——與 Warzone 2.0 共享進度。','武器平台與槍機共享；內容延續至 MWIII。'] },
    mw3:{ highlights:['最終確定 MWII 武器、Operator 與組合包的 Carry-Forward。','Modern Warfare Zombies（MWZ）階級與任務收官。','賽季 Prestige Master（至 1000）獎勵全部輪換。'], matchmaking:'在 MP、Warzone 與 MWZ 中融合技術、連線與近期表現的技術配對；房間在每局解散。', tiers:[{req:'在 55 級重置',reward:'威望徽章 + 賽季重置'},{req:'依賽季',reward:'每 50 級的賽季威望圖示'},{req:'越過威望 10 後',reward:'Master 等級 1–1000'},{req:'賽季刷取',reward:'Prestige Master 名片與圖示'}], rs:['Carry-Forward：所有 MWII 武器、Operator 與藍圖均轉入。','透過 HQ 與 Warzone 及 MWZ 統一進度與 Battle Pass。'] },
    bo6:{ highlights:['Omnimovement 調整：衝刺-滑鏟-俯衝平衡與後座力調整。','賽季武器新增與 meta 平衡調整。','Zombies 地圖、Easter egg 與 Prestige Master 獎勵輪換。','Warzone 整合：共享庫存與 Battle Pass 同步。'], matchmaking:'技術配對每局融合技術、連線與近期表現；房間在每局後解散。Ranked Play 增加可見的基於 SR 的技術分段階梯。', rs:['透過 Call of Duty HQ 與 Warzone 統一進度。','Carry Forward：符合條件的 MWII/MWIII 內容仍可在 Warzone 使用（BO6 MP 除外）。','Battle Pass 與威望在 BO6 MP、Zombies 與 Warzone 間共享。'], roadmap:[{q:'賽季進行中',item:'持續進行：每次中/大型賽季更新帶來新的 MP 地圖、武器與 Zombies 內容。'},{q:'RANKED PLAY',item:'帶技術分段、SR 與軍階鎖定獎勵的競技賽季。'},{q:'WARZONE',item:'持續整合，Resurgence 與 BR 地圖輪換與賽季掛鉤。'}] },
    bo7:{ highlights:['發行多人、Zombies 與戰役即時上線，附帶首日平衡調整。','精煉的 Omnimovement 與全新的配裝/專長系統。','地圖、武器與活動的賽季路線圖進行中。','完整整合 Call of Duty HQ 與 Warzone 進度。'], matchmaking:'技術配對每局融合技術、連線與近期表現；房間在每局後解散。Ranked Play 攜 SR 分段與賽季獎勵回歸。', rs:['與 Warzone 一同延續統一的 Call of Duty HQ 進度。','威望與 Battle Pass 在 MP、Zombies 與 Warzone 間共享。','部分 BO6 時代內容轉入共享生態。'], roadmap:[{q:'發行',item:'第 1 賽季上線：發行地圖、武器與 Ranked Play 季前賽。'},{q:'賽季中期',item:'Reloaded 更新新增地圖、武器、活動與 Zombies 內容。'},{q:'持續進行',item:'持續的 Warzone 整合與賽季 Battle Pass 節奏。'}] },
    mw4:{ highlights:['尚無官方修補說明——本作未確認。','預計將延續 Call of Duty HQ 統一進度。','佔位板塊——待 Activision 公布詳情後填寫。'], matchmaking:'預計採用與近期作品一致的技術配對（技術 + 連線 + 近期表現，房間每局解散）。未確認。', tiers:[{req:'等待公布',reward:'軍階與威望結構尚未公布。'}], rs:['預計透過 Call of Duty HQ 與 Warzone 關聯。','Carry-Forward 支援在公布前未確認。'], roadmap:[{q:'未確認',item:'無官方公告。這是社群期待的下一作的佔位內容。'}] },
  },
};

const KO = {
  pv: { finalTitle:'최종 타이틀 업데이트', finalSeasonal:'최종 시즌 업데이트', currentSeason:'현재 시즌', launchSeason:'출시 시즌', unannounced:'미발표' },
  pd: { legacy:'레거시 빌드', live:'라이브 서비스 · 시즌마다 업데이트', awaiting:'공식 공개 대기 중' },
  stdReq: ['최고 계급에서 초기화', '다섯 번 초기화', '최종 프레스티지', '프레스티지 이후 파밍'],
  stdReward: ['프레스티지 엠블럼, 콜링 카드 및 새로운 잠금 해제 진행', '초기화를 넘어 무기/특전을 유지하는 영구 잠금 해제 토큰', '보너스 클래스 슬롯, 프레스티지 아이콘 및 Prestige Shop 이용', 'Dark Ops / Master 콜링 카드 및 레거시 엠블럼'],
  statusQ:'상태', legacyItem:'레거시 타이틀 — 추가 콘텐츠 업데이트 계획이 없습니다. 온라인 플레이를 위해 서버는 계속 온라인으로 유지됩니다.',
  g: {
    bo1:{ highlights:['핵심 MP 무기와 장비의 최종 밸런스 조정.','내기 매치를 위한 Contracts와 COD Points 경제 확정.','온라인 플레이를 위한 전용 서버와 안티치트 유지 관리.'], matchmaking:'매치 사이에 로비가 유지되는 연결 우선 로비 — SBMM 이전 시대. 호스트/전용 하이브리드로, 플레이어는 게임 간에 함께 유지됩니다.', tiers:[{req:'계급 50에서 초기화',reward:'프레스티지 엠블럼 + Prestige Token으로 영구 잠금 해제 1개'},{req:'열 번 초기화',reward:'프레스티지마다 추가 Create-a-Class 슬롯'},{req:'최종 프레스티지',reward:'최대 잠금 해제 토큰, 전용 엠블럼 및 Fall 콜링 카드'},{req:'모든 프레스티지',reward:'모든 잠금 해제 환불 / 영구 잠금 해제 선택'}], rs:['독립 진행 — 타이틀 간 이월 없음.','프레스티지 잠금 해제와 COD Points는 Black Ops (2010) 내에 유지됩니다.'] },
    bo2:{ highlights:['모든 클래스에서 Pick 10 로드아웃 밸런스 확정.','League Play 디비전과 랭크 시즌 마무리.','스코어 스트릭 조정 및 최종 무기 변경.'], matchmaking:'연결 기반 매치메이킹과 선택적 실력 랭크 League Play 디비전(브론즈 → 마스터). 캐주얼 플레이리스트는 연결을 우선합니다.', rs:['독립 진행 — 잠금 해제는 Black Ops II로 제한.','Prestige Master는 이 타이틀 내에서 모든 아이템을 영구 잠금 해제합니다.'] },
    bo3:{ highlights:['스페셜리스트 능력과 무기 밸런스 확정.','Black Market / 보급 드롭 코스메틱을 로테이션으로 모두 잠금 해제.','Zombies Chronicles 맵 팩 통합 및 수정.'], matchmaking:'Arena 랭크 시즌이 있는 실력 영향형 매치메이킹. 표준 플레이리스트는 연결과 최근 성과를 반영합니다.', rs:['독립 진행 — HQ/Warzone 연동 없음(Warzone 이전).','Master Prestige(1000까지)는 프레스티지 전용 콜링 카드와 아이콘을 부여합니다.'] },
    bo4:{ highlights:['스페셜리스트와 수동 치유 밸런스 확정.','Blackout 배틀로얄 맵과 차량 조정 마무리.','Black Market Contraband 단계 보상 모두 배치.'], matchmaking:'MP와 Blackout 전반의 실력 기반 매치메이킹으로 최근 성과와 연결을 반영하며, 로비는 매 매치 후 해산됩니다.', rs:['독립 진행 — Blackout, MP, Zombies가 하나의 계정 레벨을 공유.','Contraband/Black Market 단계는 시즌마다 코스메틱을 잠금 해제합니다.'] },
    mw2019:{ highlights:['모든 플랫폼에서 Gunsmith와 무기 밸런스 확정.','Warzone(Verdansk) 통합과 로드아웃 조정 마무리.','시즌 장교 계급 보상 모두 순환.'], matchmaking:'매치마다 실력, 연결, 최근 결과를 결합하는 실력 기반 매치메이킹. 로비는 매 게임 해산됩니다(유지 없음).', tiers:[{req:'기본 상한',reward:'프레스티지와 시즌 장교 진행 잠금 해제'},{req:'55 이후, 시즌마다',reward:'Battle Pass 단계, 무기 및 Warzone 코스메틱'},{req:'시즌 파밍',reward:'시즌 전용 엠블럼, 콜링 카드 및 무기 참'},{req:'시즌 최대',reward:'최고 시즌 보상 + 프레스티지 아이콘'}], rs:['원조 Warzone(Verdansk 시대)와 진행 공유.','잠금 해제/청사진은 원조 Warzone에서 사용 가능하며, 이후 HQ 타이틀과는 연동되지 않습니다.'] },
    cw:{ highlights:['Warzone과의 게임 간 무기 밸런스 마무리.','시즌 Prestige Master(레벨 1000까지) 보상 모두 순환.','Zombies Outbreak과 라운드 기반 조정 마무리.'], matchmaking:'실력, 연결, 최근 성과를 반영하는 실력 기반 매치메이킹; 로비는 매 매치 해산. 랭크 방식의 시즌 프레스티지 초기화 포함.', tiers:[{req:'55에서 초기화',reward:'프레스티지 엠블럼 + 시즌 진행 초기화'},{req:'시즌제',reward:'시즌 전용 아이콘; 시즌 프레스티지 레벨 유지'},{req:'모든 프레스티지 이후',reward:'Master 레벨 1–1000 이용'},{req:'시즌 파밍',reward:'Prestige Master 콜링 카드와 영구 아이콘'}], rs:['통합 상한을 통해 Warzone(2020–2021 시대)과 레벨, Battle Pass, 무기 공유.','여기서 획득한 청사진과 Operator는 Warzone에서 사용 가능.'] },
    mw2:{ highlights:['무기 플랫폼/리시버 진행 확정.','Warzone 2.0과 DMZ 통합 조정 마무리.','시즌 프레스티지 계급(시즌당 250까지) 모두 순환.'], matchmaking:'MP와 Warzone 전반에서 실력, 연결, 최근 성과를 결합하는 실력 기반 매치메이킹; 로비는 매 매치 해산.', tiers:[{req:'기본 상한',reward:'시즌 프레스티지 진행 잠금 해제'},{req:'시즌마다',reward:'레벨 50/100/150/200/250의 시즌 프레스티지 아이콘'},{req:'시즌 최대',reward:'시즌 전용 무기 청사진과 엠블럼'},{req:'시즌마다',reward:'HQ를 통한 무기, Operator 및 Warzone 코스메틱'}], rs:['Call of Duty HQ의 기반 — Warzone 2.0과 진행 공유.','무기 플랫폼과 리시버 공유; 콘텐츠는 MWIII로 이월.'] },
    mw3:{ highlights:['MWII 무기, Operator, 번들의 Carry-Forward 확정.','Modern Warfare Zombies(MWZ) 단계와 미션 마무리.','시즌 Prestige Master(1000까지) 보상 모두 순환.'], matchmaking:'MP, Warzone, MWZ 전반에서 실력, 연결, 최근 성과를 결합하는 실력 기반 매치메이킹; 로비는 매 매치 해산.', tiers:[{req:'55에서 초기화',reward:'프레스티지 엠블럼 + 시즌 초기화'},{req:'시즌마다',reward:'50레벨마다 시즌 프레스티지 아이콘'},{req:'프레스티지 10 이후',reward:'Master 레벨 1–1000'},{req:'시즌 파밍',reward:'Prestige Master 콜링 카드와 아이콘'}], rs:['Carry-Forward: 모든 MWII 무기, Operator, 청사진이 이월.','HQ를 통해 Warzone 및 MWZ와 진행과 Battle Pass 통합.'] },
    bo6:{ highlights:['Omnimovement 조정: 스프린트-슬라이드-다이브 밸런스와 반동 조정.','시즌 무기 추가와 메타 밸런스 조정.','Zombies 맵, Easter egg, Prestige Master 보상 순환.','Warzone 통합: 인벤토리 공유와 Battle Pass 동기화.'], matchmaking:'실력 기반 매치메이킹은 매 매치 실력, 연결, 최근 성과를 결합하며 로비는 매 게임 후 해산됩니다. Ranked Play는 SR 기반의 가시적 실력 디비전 사다리를 추가합니다.', rs:['Call of Duty HQ를 통해 Warzone과 진행 통합.','Carry Forward: 대상 MWII/MWIII 콘텐츠는 Warzone에서 계속 사용 가능(BO6 MP에서는 불가).','Battle Pass와 프레스티지를 BO6 MP, Zombies, Warzone에서 공유.'], roadmap:[{q:'시즌 중',item:'진행 중: 중/대형 시즌 업데이트마다 새 MP 맵, 무기, Zombies 콘텐츠.'},{q:'RANKED PLAY',item:'실력 디비전, SR, 계급 잠금 보상이 있는 경쟁 시즌.'},{q:'WARZONE',item:'지속적 통합, 시즌에 연동된 Resurgence·BR 맵 로테이션.'}] },
    bo7:{ highlights:['출시 멀티플레이어, Zombies, 캠페인이 첫날 밸런스 조정과 함께 라이브.','정교해진 Omnimovement와 새로워진 로드아웃/특전 시스템.','맵, 무기, 이벤트의 시즌 로드맵 진행 중.','Call of Duty HQ와 Warzone 진행 완전 통합.'], matchmaking:'실력 기반 매치메이킹은 매 매치 실력, 연결, 최근 성과를 결합하며 로비는 매 게임 후 해산됩니다. Ranked Play는 SR 디비전과 시즌 보상과 함께 돌아옵니다.', rs:['Warzone과 함께 통합 Call of Duty HQ 진행 지속.','프레스티지와 Battle Pass를 MP, Zombies, Warzone에서 공유.','일부 BO6 시대 콘텐츠가 공유 생태계로 이월됩니다.'], roadmap:[{q:'출시',item:'시즌 1 라이브: 출시 맵, 무기, Ranked Play 프리시즌.'},{q:'시즌 중반',item:'Reloaded 드롭이 맵, 무기, 이벤트, Zombies 콘텐츠를 추가.'},{q:'진행 중',item:'지속적인 Warzone 통합과 시즌 Battle Pass 주기.'}] },
    mw4:{ highlights:['아직 공식 패치 노트 없음 — 이 타이틀은 미확정입니다.','Call of Duty HQ 통합 진행을 이어갈 것으로 예상.','자리 표시 섹션 — Activision이 세부 정보를 발표하면 채워집니다.'], matchmaking:'최근 타이틀과 일관된 실력 기반 매치메이킹(실력 + 연결 + 최근 성과, 로비는 매 매치 해산)을 사용할 것으로 예상. 미확정.', tiers:[{req:'공개 대기 중',reward:'계급 및 프레스티지 구조 아직 미발표.'}], rs:['Call of Duty HQ를 통해 Warzone과 연동될 것으로 예상.','Carry-Forward 지원은 공개 전까지 미확정.'], roadmap:[{q:'미확정',item:'공식 발표 없음. 커뮤니티가 기대하는 다음 타이틀의 자리 표시입니다.'}] },
  },
};

export const SEL2 = { ja: build(JA), zh: build(ZH), zhTw: build(ZHTW), ko: build(KO) };
