// Deep dossier translations — batch 1: de, es, fr, it, pt.
// Composed into SEL[lang][gameId] = { patchVersion, patchDate, highlights, matchmaking, tiers, rewardSupport, roadmap }
// and merged into each game dossier at runtime (works offline / hosted, no AI needed).
// Proper nouns kept in English (Black Ops, Modern Warfare, Warzone, Prestige, Nuketown, Blackout, Omnimovement,
// RICOCHET, Battle Pass, Call of Duty HQ, Zombies, Blackout, MWZ, DMZ, Verdansk, Gunsmith, Pick 10, Carry-Forward, etc.).

const META = { bo1:['finalTitle','legacy'], bo2:['finalTitle','legacy'], bo3:['finalTitle','legacy'], bo4:['finalTitle','legacy'], mw2019:['finalSeasonal','legacy'], cw:['finalSeasonal','legacy'], mw2:['finalSeasonal','legacy'], mw3:['finalSeasonal','legacy'], bo6:['currentSeason','live'], bo7:['launchSeason','live'], mw4:['unannounced','awaiting'] };
const STDMAX = { bo2:['10','Master'], bo3:['10','1000'], bo4:['10','Master'], bo6:['10','1000'], bo7:['10','1000'] };
const TN = { bo1:['Prestige 1','Prestige 10','Prestige 15','Prestige Shop'], mw2019:['Rank 55','Season Level 1','Officer Rank','Officer 155'], cw:['Prestige 1','Prestige 3','Prestige Master','Master 1000'], mw2:['Rank 55','Prestige 1–5','Season Level 250','Battle Pass'], mw3:['Prestige 1','Prestige 10','Prestige Master','Master 1000'], mw4:['TBA'] };
const CUSTOM_ROAD = ['bo6','bo7','mw4'];

function build(L) {
  const out = {};
  Object.keys(META).forEach(gid => {
    const g = L.g[gid];
    const [pvk, pdk] = META[gid];
    let tiers;
    if (STDMAX[gid]) {
      const [max, master] = STDMAX[gid];
      const nm = ['Prestige 1', 'Prestige 5', 'Prestige ' + max, 'Master ' + master];
      tiers = nm.map((name, i) => ({ name, req: L.stdReq[i], reward: L.stdReward[i] }));
    } else {
      tiers = TN[gid].map((name, i) => ({ name, req: g.tiers[i].req, reward: g.tiers[i].reward }));
    }
    const roadmap = CUSTOM_ROAD.includes(gid) ? g.roadmap : [{ q: L.statusQ, item: L.legacyItem }];
    out[gid] = { patchVersion: L.pv[pvk], patchDate: L.pd[pdk], highlights: g.highlights, matchmaking: g.matchmaking, tiers, rewardSupport: g.rs, roadmap };
  });
  return out;
}

const DE = {
  pv: { finalTitle:'LETZTES TITEL-UPDATE', finalSeasonal:'LETZTES SAISONALES UPDATE', currentSeason:'AKTUELLE SEASON', launchSeason:'START-SEASON', unannounced:'UNANGEKÜNDIGT' },
  pd: { legacy:'Legacy-Build', live:'Live-Service · saisonal aktualisiert', awaiting:'Offizielle Enthüllung ausstehend' },
  stdReq: ['Zurücksetzen bei Maximalrang', 'Fünf Resets', 'Letztes Prestige', 'Grind nach dem Prestige'],
  stdReward: ['Prestige-Emblem, Visitenkarte & neuer Freischalt-Fortschritt', 'Permanentes Freischalt-Token, um eine Waffe/ein Perk über Resets zu behalten', 'Bonus-Klassenslots, Prestige-Symbol & Zugang zum Prestige Shop', 'Dark Ops / Master-Visitenkarte & Legacy-Emblem'],
  statusQ:'STATUS', legacyItem:'Legacy-Titel — keine weiteren Inhalts-Updates geplant. Die Server bleiben für das Online-Spiel online.',
  g: {
    bo1:{ highlights:['Letzter Balance-Durchgang für Kern-MP-Waffen und -Ausrüstung.','Contract- & COD-Points-Wirtschaft für Wettkämpfe finalisiert.','Dedicated-Server- & Anti-Cheat-Wartung für das Online-Spiel.'], matchmaking:'Verbindungsorientierte Lobbys mit Lobby-Persistenz zwischen Matches — Ära vor SBMM. Host/Dedicated-Hybrid; Spieler bleiben über Spiele hinweg zusammen.', tiers:[{req:'Reset bei Rang 50',reward:'Prestige-Emblem + eine permanente Freischaltung per Prestige Token'},{req:'Zehn Resets',reward:'Zusätzlicher Create-a-Class-Slot pro Prestige'},{req:'Letztes Prestige',reward:'Maximale Freischalt-Tokens, exklusives Emblem & Fall-Visitenkarte'},{req:'Beliebiges Prestige',reward:'Alle Freischaltungen erstatten / permanente Freischaltung wählen'}], rs:['Eigenständiger Fortschritt — kein titelübergreifender Carry-Forward.','Prestige-Freischaltungen und COD Points bleiben in Black Ops (2010).'] },
    bo2:{ highlights:['Pick-10-Loadout-Balance über alle Klassen finalisiert.','League-Play-Divisionen & Ranglisten-Seasons abgeschlossen.','Score-Streak-Anpassung und letzte Waffenänderungen.'], matchmaking:'Verbindungsbasiertes Matchmaking mit optionalen skill-basierten League-Play-Divisionen (Bronze → Master). Casual-Playlists bevorzugen die Verbindung.', rs:['Eigenständiger Fortschritt — Freischaltungen auf Black Ops II beschränkt.','Prestige Master schaltet alle Objekte innerhalb dieses Titels dauerhaft frei.'] },
    bo3:{ highlights:['Spezialisten-Fähigkeiten- & Waffenbalance finalisiert.','Black-Market-/Supply-Drop-Kosmetik vollständig in Rotation freigeschaltet.','Integration und Fixes des Zombies-Chronicles-Kartenpakets.'], matchmaking:'Skill-beeinflusstes Matchmaking mit Arena-Ranglisten-Seasons. Standard-Playlists gewichten Verbindung und jüngste Leistung.', rs:['Eigenständiger Fortschritt — keine HQ-/Warzone-Verknüpfung (vor Warzone).','Master Prestige (bis 1000) gewährt prestige-exklusive Visitenkarten & Symbole.'] },
    bo4:{ highlights:['Spezialisten- und manuelle Heilungs-Balance finalisiert.','Blackout-Battle-Royale-Karte & Fahrzeug-Tuning abgeschlossen.','Black-Market-Contraband-Stufenbelohnungen vollständig eingespielt.'], matchmaking:'Skill-basiertes Matchmaking über MP und Blackout, gewichtet jüngste Leistung und Verbindung; Lobbys lösen sich nach jedem Match auf.', rs:['Eigenständiger Fortschritt — Blackout, MP und Zombies teilen eine Konto-Stufe.','Contraband-/Black-Market-Stufen schalten saisonale Kosmetik frei.'] },
    mw2019:{ highlights:['Gunsmith- und Waffenbalance plattformübergreifend finalisiert.','Warzone-(Verdansk-)Integration und Loadout-Anpassung abgeschlossen.','Saisonale Offiziersrang-Belohnungen vollständig rotiert.'], matchmaking:'Skill-basiertes Matchmaking, das Skill, Verbindung und jüngste Ergebnisse pro Match kombiniert. Lobbys lösen sich nach jedem Spiel auf (keine Persistenz).', tiers:[{req:'Basis-Obergrenze',reward:'Schaltet Prestige & saisonalen Offiziers-Fortschritt frei'},{req:'Nach 55, pro Season',reward:'Battle-Pass-Stufen, Waffen & Warzone-Kosmetik'},{req:'Saisonaler Grind',reward:'Season-exklusive Embleme, Visitenkarten & Waffenanhänger'},{req:'Saisonales Maximum',reward:'Top-Saisonbelohnung + Prestige-Symbol'}], rs:['Geteilter Fortschritt mit dem originalen Warzone (Verdansk-Ära).','Freischaltungen/Baupläne im originalen Warzone nutzbar; nicht mit späteren HQ-Titeln verknüpft.'] },
    cw:{ highlights:['Spielübergreifende Waffenbalance mit Warzone finalisiert.','Saisonale Prestige-Master-Belohnungen (bis Level 1000) vollständig rotiert.','Zombies Outbreak & rundenbasiertes Tuning abgeschlossen.'], matchmaking:'Skill-basiertes Matchmaking, das Skill, Verbindung und jüngste Leistung gewichtet; Lobbys lösen sich nach jedem Match auf. Ranglisten-artige saisonale Prestige-Resets.', tiers:[{req:'Reset bei 55',reward:'Prestige-Emblem + saisonaler Fortschritts-Reset'},{req:'Saisonal',reward:'Season-exklusives Symbol; überträgt saisonales Prestige-Level'},{req:'Nach allen Prestiges',reward:'Zugang zu Master-Leveln 1–1000'},{req:'Saisonaler Grind',reward:'Prestige-Master-Visitenkarte & permanentes Symbol'}], rs:['Geteiltes Level, Battle Pass & Waffen mit Warzone (2020–2021-Ära) über eine gemeinsame Obergrenze.','Hier verdiente Baupläne und Operator in Warzone nutzbar.'] },
    mw2:{ highlights:['Waffenplattform-/Receiver-Fortschritt finalisiert.','Warzone-2.0- & DMZ-Integrationsanpassung abgeschlossen.','Saisonale Prestige-Ränge (bis 250 pro Season) vollständig rotiert.'], matchmaking:'Skill-basiertes Matchmaking über MP und Warzone, das Skill, Verbindung und jüngste Leistung kombiniert; Lobbys lösen sich nach jedem Match auf.', tiers:[{req:'Basis-Obergrenze',reward:'Schaltet saisonalen Prestige-Fortschritt frei'},{req:'Pro Season',reward:'Saisonale Prestige-Symbole auf Level 50/100/150/200/250'},{req:'Saisonales Maximum',reward:'Season-exklusiver Waffenbauplan & Emblem'},{req:'Pro Season',reward:'Waffen, Operator & Warzone-Kosmetik über HQ'}], rs:['Grundlage von Call of Duty HQ — geteilter Fortschritt mit Warzone 2.0.','Waffenplattformen & Receiver geteilt; Inhalte in MWIII übernommen.'] },
    mw3:{ highlights:['Carry-Forward von MWII-Waffen, -Operatoren & -Bundles finalisiert.','Modern Warfare Zombies (MWZ) Stufen und Missionen abgeschlossen.','Saisonale Prestige-Master-Belohnungen (bis 1000) vollständig rotiert.'], matchmaking:'Skill-basiertes Matchmaking, das Skill, Verbindung und jüngste Leistung über MP, Warzone und MWZ kombiniert; Lobbys lösen sich nach jedem Match auf.', tiers:[{req:'Reset bei 55',reward:'Prestige-Emblem + saisonaler Reset'},{req:'Pro Season',reward:'Saisonale Prestige-Symbole alle 50 Level'},{req:'Nach Prestige 10',reward:'Master-Level 1–1000'},{req:'Saisonaler Grind',reward:'Prestige-Master-Visitenkarte & Symbol'}], rs:['Carry-Forward: alle MWII-Waffen, -Operatoren & -Baupläne werden übernommen.','Einheitlicher Fortschritt & Battle Pass mit Warzone und MWZ über HQ.'] },
    bo6:{ highlights:['Omnimovement-Anpassung: Sprint-Slide-Dive-Balance und Rückstoß-Durchgang.','Saisonale Waffen-Ergänzungen und Meta-Balance-Anpassungen.','Rotation von Zombies-Karte, Easter Egg und Prestige-Master-Belohnungen.','Warzone-Integration: geteiltes Inventar und Battle-Pass-Sync.'], matchmaking:'Skill-basiertes Matchmaking kombiniert Skill, Verbindung und jüngste Leistung in jedem Match; Lobbys lösen sich nach jedem Spiel auf. Ranked Play fügt eine sichtbare SR-basierte Skill-Divisionsleiter hinzu.', rs:['Einheitlicher Fortschritt mit Warzone über Call of Duty HQ.','Carry Forward: berechtigte MWII/MWIII-Inhalte bleiben in Warzone nutzbar (nicht im BO6-MP).','Battle Pass & Prestige geteilt über BO6-MP, Zombies und Warzone.'], roadmap:[{q:'IN DER SEASON',item:'Laufend: neue MP-Karten, Waffen und Zombies-Inhalte bei jedem Mid-/Major-Season-Update.'},{q:'RANKED PLAY',item:'Kompetitive Seasons mit Skill-Divisionen, SR und rang-gebundenen Belohnungen.'},{q:'WARZONE',item:'Fortlaufende Integration, Resurgence- & BR-Kartenrotationen an die Season gebunden.'}] },
    bo7:{ highlights:['Start von Multiplayer, Zombies und Kampagne mit Day-One-Balance-Durchgang.','Verfeinertes Omnimovement und überarbeitetes Loadout-/Perk-System.','Saisonale Roadmap aus Karten, Waffen und Events im Gange.','Vollständige Call-of-Duty-HQ- & Warzone-Fortschrittsintegration.'], matchmaking:'Skill-basiertes Matchmaking kombiniert Skill, Verbindung und jüngste Leistung in jedem Match; Lobbys lösen sich nach jedem Spiel auf. Ranked Play kehrt mit SR-Divisionen und saisonalen Belohnungen zurück.', rs:['Setzt den einheitlichen Call-of-Duty-HQ-Fortschritt mit Warzone fort.','Prestige & Battle Pass geteilt über MP, Zombies und Warzone.','Ausgewählte BO6-Inhalte werden in das geteilte Ökosystem übernommen.'], roadmap:[{q:'START',item:'Season 1 live: Start-Karten, Waffen und Ranked-Play-Vorsaison.'},{q:'MID-SEASON',item:'Reloaded-Drops fügen Karten, Waffen, Events und Zombies-Inhalte hinzu.'},{q:'LAUFEND',item:'Fortlaufende Warzone-Integration und saisonaler Battle-Pass-Rhythmus.'}] },
    mw4:{ highlights:['Noch keine offiziellen Patchnotes — dieser Teil ist unbestätigt.','Erwartet wird die Fortführung des einheitlichen Call-of-Duty-HQ-Fortschritts.','Platzhalter-Abschnitt — wird ausgefüllt, sobald Activision Details bekannt gibt.'], matchmaking:'Voraussichtlich skill-basiertes Matchmaking im Einklang mit aktuellen Titeln (Skill + Verbindung + jüngste Leistung, Lobbys lösen sich nach jedem Match auf). Unbestätigt.', tiers:[{req:'Enthüllung ausstehend',reward:'Rang- & Prestige-Struktur noch nicht angekündigt.'}], rs:['Voraussichtliche Verknüpfung mit Warzone über Call of Duty HQ.','Carry-Forward-Unterstützung bis zur Enthüllung unbestätigt.'], roadmap:[{q:'UNBESTÄTIGT',item:'Keine offizielle Ankündigung. Dies ist ein Platzhalter für den von der Community erwarteten nächsten Teil.'}] },
  },
};

const ES = {
  pv: { finalTitle:'ÚLTIMA ACTUALIZACIÓN DEL TÍTULO', finalSeasonal:'ÚLTIMA ACTUALIZACIÓN DE TEMPORADA', currentSeason:'TEMPORADA ACTUAL', launchSeason:'TEMPORADA DE LANZAMIENTO', unannounced:'SIN ANUNCIAR' },
  pd: { legacy:'Versión heredada', live:'Servicio en vivo · actualizado por temporadas', awaiting:'A la espera de la revelación oficial' },
  stdReq: ['Reinicio al rango máximo', 'Cinco reinicios', 'Prestigio final', 'Farmeo tras el prestigio'],
  stdReward: ['Emblema de prestigio, tarjeta de presentación y nuevo progreso de desbloqueo', 'Ficha de desbloqueo permanente para conservar un arma/ventaja entre reinicios', 'Ranuras de clase adicionales, ícono de prestigio y acceso a la Prestige Shop', 'Tarjeta de presentación Dark Ops / Master y emblema heredado'],
  statusQ:'ESTADO', legacyItem:'Título heredado — sin más actualizaciones de contenido previstas. Los servidores siguen en línea para el juego en línea.',
  g: {
    bo1:{ highlights:['Último ajuste de equilibrio de las armas y el equipo principales del MP.','Economía de Contracts y COD Points finalizada para las partidas de apuestas.','Mantenimiento de servidores dedicados y anti-trampas para el juego en línea.'], matchmaking:'Salas basadas en la conexión con persistencia de sala entre partidas — era anterior al SBMM. Híbrido host/dedicado; los jugadores permanecen juntos entre partidas.', tiers:[{req:'Reinicio en el rango 50',reward:'Emblema de prestigio + un desbloqueo permanente con Prestige Token'},{req:'Diez reinicios',reward:'Ranura extra de Create-a-Class por prestigio'},{req:'Prestigio final',reward:'Máximas fichas de desbloqueo, emblema exclusivo y tarjeta Fall'},{req:'Cualquier prestigio',reward:'Reembolsar todos los desbloqueos / elegir desbloqueo permanente'}], rs:['Progreso independiente — sin traspaso entre títulos.','Los desbloqueos de prestigio y los COD Points quedan dentro de Black Ops (2010).'] },
    bo2:{ highlights:['Equilibrio del equipamiento Pick 10 finalizado en todas las clases.','Divisiones de League Play y temporadas clasificatorias cerradas.','Ajuste de rachas de puntos y cambios finales de armas.'], matchmaking:'Emparejamiento basado en la conexión con divisiones opcionales de League Play por habilidad (Bronce → Maestro). Las listas casuales priorizan la conexión.', rs:['Progreso independiente — desbloqueos limitados a Black Ops II.','Prestige Master desbloquea todos los objetos de forma permanente dentro de este título.'] },
    bo3:{ highlights:['Equilibrio de habilidades de especialista y armas finalizado.','Cosméticos de Black Market / supply drop desbloqueados en rotación.','Integración y correcciones del paquete de mapas Zombies Chronicles.'], matchmaking:'Emparejamiento influido por la habilidad con temporadas clasificatorias de Arena. Las listas estándar ponderan la conexión y el rendimiento reciente.', rs:['Progreso independiente — sin vínculo con HQ/Warzone (anterior a Warzone).','Master Prestige (hasta 1000) otorga tarjetas e íconos exclusivos de prestigio.'] },
    bo4:{ highlights:['Equilibrio de especialistas y curación manual finalizado.','Ajuste del mapa y vehículos de la battle royale Blackout cerrado.','Recompensas por niveles de Black Market Contraband totalmente sembradas.'], matchmaking:'Emparejamiento por habilidad en MP y Blackout, ponderando el rendimiento reciente y la conexión; las salas se disuelven tras cada partida.', rs:['Progreso independiente — Blackout, MP y Zombies comparten un nivel de cuenta.','Los niveles de Contraband/Black Market desbloquean cosméticos por temporadas.'] },
    mw2019:{ highlights:['Equilibrio de Gunsmith y armas finalizado en todas las plataformas.','Integración de Warzone (Verdansk) y ajuste de equipamiento cerrados.','Recompensas estacionales de rango de Oficial totalmente rotadas.'], matchmaking:'Emparejamiento por habilidad que combina habilidad, conexión y resultados recientes por partida. Las salas se disuelven en cada juego (sin persistencia).', tiers:[{req:'Tope base',reward:'Desbloquea Prestigio y progreso estacional de Oficial'},{req:'Tras el 55, por temporada',reward:'Niveles de Battle Pass, armas y cosméticos de Warzone'},{req:'Farmeo estacional',reward:'Emblemas, tarjetas y amuletos de arma exclusivos de temporada'},{req:'Máximo estacional',reward:'Máxima recompensa estacional + ícono de prestigio'}], rs:['Progreso compartido con el Warzone original (era Verdansk).','Desbloqueos/planos usables en el Warzone original; no vinculados a títulos HQ posteriores.'] },
    cw:{ highlights:['Equilibrio de armas entre juegos con Warzone finalizado.','Recompensas de Prestige Master estacional (hasta nivel 1000) totalmente rotadas.','Zombies Outbreak y ajuste por rondas cerrados.'], matchmaking:'Emparejamiento por habilidad que pondera habilidad, conexión y rendimiento reciente; las salas se disuelven en cada partida. Reinicios de prestigio estacional al estilo clasificatorio.', tiers:[{req:'Reinicio en 55',reward:'Emblema de prestigio + reinicio de progreso estacional'},{req:'Estacional',reward:'Ícono exclusivo de temporada; conserva el nivel de prestigio estacional'},{req:'Tras todos los prestigios',reward:'Acceso a los niveles Master 1–1000'},{req:'Farmeo estacional',reward:'Tarjeta de Prestige Master e ícono permanente'}], rs:['Nivel, Battle Pass y armas compartidos con Warzone (era 2020–2021) mediante un tope unificado.','Los planos y Operadores obtenidos aquí son usables en Warzone.'] },
    mw2:{ highlights:['Progreso de plataforma de arma / receptor finalizado.','Ajuste de integración de Warzone 2.0 y DMZ cerrado.','Rangos de prestigio estacional (hasta 250 por temporada) totalmente rotados.'], matchmaking:'Emparejamiento por habilidad en MP y Warzone, combinando habilidad, conexión y rendimiento reciente; las salas se disuelven en cada partida.', tiers:[{req:'Tope base',reward:'Desbloquea el progreso de prestigio estacional'},{req:'Por temporada',reward:'Íconos de prestigio estacional en los niveles 50/100/150/200/250'},{req:'Máximo estacional',reward:'Plano de arma y emblema exclusivos de temporada'},{req:'Por temporada',reward:'Armas, Operadores y cosméticos de Warzone vía HQ'}], rs:['Base de Call of Duty HQ — progreso compartido con Warzone 2.0.','Plataformas de arma y receptores compartidos; contenido trasladado a MWIII.'] },
    mw3:{ highlights:['Carry-Forward de armas, Operadores y paquetes de MWII finalizado.','Niveles y misiones de Modern Warfare Zombies (MWZ) cerrados.','Recompensas de Prestige Master estacional (hasta 1000) totalmente rotadas.'], matchmaking:'Emparejamiento por habilidad que combina habilidad, conexión y rendimiento reciente en MP, Warzone y MWZ; las salas se disuelven en cada partida.', tiers:[{req:'Reinicio en 55',reward:'Emblema de prestigio + reinicio estacional'},{req:'Por temporada',reward:'Íconos de prestigio estacional cada 50 niveles'},{req:'Tras el prestigio 10',reward:'Niveles Master 1–1000'},{req:'Farmeo estacional',reward:'Tarjeta de Prestige Master e ícono'}], rs:['Carry-Forward: todas las armas, Operadores y planos de MWII se trasladan.','Progreso y Battle Pass unificados con Warzone y MWZ vía HQ.'] },
    bo6:{ highlights:['Ajuste de Omnimovement: equilibrio de sprint-deslizamiento-clavado y retroceso.','Adiciones de armas estacionales y ajustes de equilibrio del meta.','Rotación de mapa de Zombies, Easter egg y recompensas de Prestige Master.','Integración de Warzone: inventario compartido y sincronización del Battle Pass.'], matchmaking:'El emparejamiento por habilidad combina habilidad, conexión y rendimiento reciente en cada partida; las salas se disuelven tras cada juego. Ranked Play añade una escalera visible de divisiones por SR.', rs:['Progreso unificado con Warzone a través de Call of Duty HQ.','Carry Forward: el contenido elegible de MWII/MWIII sigue siendo usable en Warzone (no en el MP de BO6).','Battle Pass y Prestigio compartidos entre el MP de BO6, Zombies y Warzone.'], roadmap:[{q:'EN TEMPORADA',item:'En curso: nuevos mapas de MP, armas y contenido de Zombies en cada actualización de media/gran temporada.'},{q:'RANKED PLAY',item:'Temporadas competitivas con divisiones por habilidad, SR y recompensas por rango.'},{q:'WARZONE',item:'Integración continua, rotaciones de mapas de Resurgence y BR ligadas a la temporada.'}] },
    bo7:{ highlights:['Multijugador, Zombies y campaña en vivo al lanzamiento con ajuste de equilibrio del primer día.','Omnimovement refinado y sistema de equipamiento/ventajas renovado.','Roadmap estacional de mapas, armas y eventos en marcha.','Integración total del progreso de Call of Duty HQ y Warzone.'], matchmaking:'El emparejamiento por habilidad combina habilidad, conexión y rendimiento reciente en cada partida; las salas se disuelven tras cada juego. Ranked Play regresa con divisiones por SR y recompensas estacionales.', rs:['Continúa el progreso unificado de Call of Duty HQ con Warzone.','Prestigio y Battle Pass compartidos entre MP, Zombies y Warzone.','Contenido selecto de la era BO6 se traslada al ecosistema compartido.'], roadmap:[{q:'LANZAMIENTO',item:'Temporada 1 en vivo: mapas de lanzamiento, armas y pretemporada de Ranked Play.'},{q:'MEDIA TEMPORADA',item:'Los drops Reloaded añaden mapas, armas, eventos y contenido de Zombies.'},{q:'EN CURSO',item:'Integración continua de Warzone y cadencia estacional del Battle Pass.'}] },
    mw4:{ highlights:['Aún no hay notas oficiales — esta entrega no está confirmada.','Se espera que continúe el progreso unificado de Call of Duty HQ.','Sección de marcador — se completará cuando Activision anuncie los detalles.'], matchmaking:'Se espera que use emparejamiento por habilidad acorde con los títulos recientes (habilidad + conexión + rendimiento reciente, las salas se disuelven en cada partida). Sin confirmar.', tiers:[{req:'A la espera de la revelación',reward:'Estructura de rango y prestigio aún no anunciada.'}], rs:['Se espera que se vincule con Warzone vía Call of Duty HQ.','Soporte de Carry-Forward sin confirmar hasta la revelación.'], roadmap:[{q:'SIN CONFIRMAR',item:'Sin anuncio oficial. Este es un marcador para la próxima entrega esperada por la comunidad.'}] },
  },
};

const FR = {
  pv: { finalTitle:'DERNIÈRE MISE À JOUR DU TITRE', finalSeasonal:'DERNIÈRE MISE À JOUR DE SAISON', currentSeason:'SAISON ACTUELLE', launchSeason:'SAISON DE LANCEMENT', unannounced:'NON ANNONCÉ' },
  pd: { legacy:'Build hérité', live:'Service en direct · mis à jour par saison', awaiting:'En attente de la révélation officielle' },
  stdReq: ['Réinitialisation au rang maximal', 'Cinq réinitialisations', 'Prestige final', 'Farm après le prestige'],
  stdReward: ['Emblème de prestige, carte de visite et nouvelle progression de déblocage', 'Jeton de déblocage permanent pour conserver une arme/un atout entre les réinitialisations', 'Emplacements de classe bonus, icône de prestige et accès à la Prestige Shop', 'Carte de visite Dark Ops / Master et emblème hérité'],
  statusQ:'STATUT', legacyItem:'Titre hérité — aucune autre mise à jour de contenu prévue. Les serveurs restent en ligne pour le jeu en ligne.',
  g: {
    bo1:{ highlights:['Dernier passage d\u2019équilibrage des armes et de l\u2019équipement MP principaux.','Économie de Contracts et de COD Points finalisée pour les parties à mise.','Maintenance des serveurs dédiés et de l\u2019anti-triche pour le jeu en ligne.'], matchmaking:'Salons axés sur la connexion avec persistance du salon entre les parties — ère pré-SBMM. Hybride host/dédié ; les joueurs restent ensemble d\u2019une partie à l\u2019autre.', tiers:[{req:'Réinitialisation au rang 50',reward:'Emblème de prestige + un déblocage permanent via Prestige Token'},{req:'Dix réinitialisations',reward:'Emplacement Create-a-Class supplémentaire par prestige'},{req:'Prestige final',reward:'Jetons de déblocage maximaux, emblème exclusif et carte Fall'},{req:'N\u2019importe quel prestige',reward:'Rembourser tous les déblocages / choisir un déblocage permanent'}], rs:['Progression autonome — pas de transfert entre titres.','Les déblocages de prestige et les COD Points restent dans Black Ops (2010).'] },
    bo2:{ highlights:['Équilibrage de l\u2019équipement Pick 10 finalisé sur toutes les classes.','Divisions League Play et saisons classées clôturées.','Réglage des séries de points et derniers ajustements d\u2019armes.'], matchmaking:'Matchmaking basé sur la connexion avec des divisions League Play classées optionnelles (Bronze → Maître). Les playlists décontractées privilégient la connexion.', rs:['Progression autonome — déblocages limités à Black Ops II.','Prestige Master débloque tous les objets de façon permanente dans ce titre.'] },
    bo3:{ highlights:['Équilibrage des capacités de spécialiste et des armes finalisé.','Cosmétiques Black Market / supply drop entièrement débloqués en rotation.','Intégration et corrections du pack de cartes Zombies Chronicles.'], matchmaking:'Matchmaking influencé par le skill avec des saisons classées Arena. Les playlists standard pondèrent la connexion et les performances récentes.', rs:['Progression autonome — pas de liaison HQ/Warzone (avant Warzone).','Master Prestige (jusqu\u2019à 1000) offre des cartes et icônes exclusives de prestige.'] },
    bo4:{ highlights:['Équilibrage des spécialistes et du soin manuel finalisé.','Réglage de la carte et des véhicules de la battle royale Blackout clôturé.','Récompenses par paliers Black Market Contraband entièrement intégrées.'], matchmaking:'Matchmaking basé sur le skill en MP et Blackout, pondérant les performances récentes et la connexion ; les salons se dissolvent après chaque partie.', rs:['Progression autonome — Blackout, MP et Zombies partagent un niveau de compte.','Les paliers Contraband/Black Market débloquent des cosmétiques par saison.'] },
    mw2019:{ highlights:['Équilibrage Gunsmith et armes finalisé sur toutes les plateformes.','Intégration de Warzone (Verdansk) et réglage de l\u2019équipement clôturés.','Récompenses saisonnières de rang d\u2019Officier entièrement alternées.'], matchmaking:'Matchmaking basé sur le skill mêlant skill, connexion et résultats récents par partie. Les salons se dissolvent à chaque partie (pas de persistance).', tiers:[{req:'Plafond de base',reward:'Débloque le Prestige et la progression saisonnière d\u2019Officier'},{req:'Après 55, par saison',reward:'Paliers de Battle Pass, armes et cosmétiques Warzone'},{req:'Farm saisonnier',reward:'Emblèmes, cartes et breloques d\u2019arme exclusifs à la saison'},{req:'Maximum saisonnier',reward:'Meilleure récompense saisonnière + icône de prestige'}], rs:['Progression partagée avec le Warzone original (ère Verdansk).','Déblocages/plans utilisables dans le Warzone original ; non liés aux titres HQ ultérieurs.'] },
    cw:{ highlights:['Équilibrage des armes inter-jeux avec Warzone finalisé.','Récompenses Prestige Master saisonnier (jusqu\u2019au niveau 1000) entièrement alternées.','Zombies Outbreak et réglage par manches clôturés.'], matchmaking:'Matchmaking basé sur le skill pondérant skill, connexion et performances récentes ; les salons se dissolvent à chaque partie. Réinitialisations de prestige saisonnier façon classé.', tiers:[{req:'Réinitialisation à 55',reward:'Emblème de prestige + réinitialisation de progression saisonnière'},{req:'Saisonnier',reward:'Icône exclusive à la saison ; conserve le niveau de prestige saisonnier'},{req:'Après tous les prestiges',reward:'Accès aux niveaux Master 1–1000'},{req:'Farm saisonnier',reward:'Carte de Prestige Master et icône permanente'}], rs:['Niveau, Battle Pass et armes partagés avec Warzone (ère 2020–2021) via un plafond unifié.','Plans et Opérateurs obtenus ici utilisables dans Warzone.'] },
    mw2:{ highlights:['Progression de plateforme d\u2019arme / receveur finalisée.','Réglage de l\u2019intégration Warzone 2.0 et DMZ clôturé.','Rangs de prestige saisonnier (jusqu\u2019à 250 par saison) entièrement alternés.'], matchmaking:'Matchmaking basé sur le skill en MP et Warzone, mêlant skill, connexion et performances récentes ; les salons se dissolvent à chaque partie.', tiers:[{req:'Plafond de base',reward:'Débloque la progression de prestige saisonnier'},{req:'Par saison',reward:'Icônes de prestige saisonnier aux niveaux 50/100/150/200/250'},{req:'Maximum saisonnier',reward:'Plan d\u2019arme et emblème exclusifs à la saison'},{req:'Par saison',reward:'Armes, Opérateurs et cosmétiques Warzone via HQ'}], rs:['Base de Call of Duty HQ — progression partagée avec Warzone 2.0.','Plateformes d\u2019arme et receveurs partagés ; contenu transféré vers MWIII.'] },
    mw3:{ highlights:['Carry-Forward des armes, Opérateurs et lots MWII finalisé.','Paliers et missions de Modern Warfare Zombies (MWZ) clôturés.','Récompenses Prestige Master saisonnier (jusqu\u2019à 1000) entièrement alternées.'], matchmaking:'Matchmaking basé sur le skill mêlant skill, connexion et performances récentes en MP, Warzone et MWZ ; les salons se dissolvent à chaque partie.', tiers:[{req:'Réinitialisation à 55',reward:'Emblème de prestige + réinitialisation saisonnière'},{req:'Par saison',reward:'Icônes de prestige saisonnier tous les 50 niveaux'},{req:'Après le prestige 10',reward:'Niveaux Master 1–1000'},{req:'Farm saisonnier',reward:'Carte de Prestige Master et icône'}], rs:['Carry-Forward : toutes les armes, Opérateurs et plans MWII sont transférés.','Progression et Battle Pass unifiés avec Warzone et MWZ via HQ.'] },
    bo6:{ highlights:['Réglage de l\u2019Omnimovement : équilibrage sprint-glissade-plongeon et passage de recul.','Ajouts d\u2019armes saisonniers et ajustements d\u2019équilibrage du méta.','Rotation de carte Zombies, Easter egg et récompenses Prestige Master.','Intégration Warzone : inventaire partagé et synchronisation du Battle Pass.'], matchmaking:'Le matchmaking basé sur le skill mêle skill, connexion et performances récentes à chaque partie ; les salons se dissolvent après chaque partie. Ranked Play ajoute une échelle visible de divisions par SR.', rs:['Progression unifiée avec Warzone via Call of Duty HQ.','Carry Forward : le contenu MWII/MWIII éligible reste utilisable dans Warzone (pas dans le MP de BO6).','Battle Pass et Prestige partagés entre le MP de BO6, Zombies et Warzone.'], roadmap:[{q:'EN SAISON',item:'En cours : nouvelles cartes MP, armes et contenu Zombies à chaque mise à jour de mi/grande saison.'},{q:'RANKED PLAY',item:'Saisons compétitives avec divisions de skill, SR et récompenses liées au rang.'},{q:'WARZONE',item:'Intégration continue, rotations de cartes Resurgence et BR liées à la saison.'}] },
    bo7:{ highlights:['Multijoueur, Zombies et campagne en direct au lancement avec passage d\u2019équilibrage du premier jour.','Omnimovement affiné et système d\u2019équipement/atouts renouvelé.','Roadmap saisonnière de cartes, armes et événements en cours.','Intégration complète de la progression Call of Duty HQ et Warzone.'], matchmaking:'Le matchmaking basé sur le skill mêle skill, connexion et performances récentes à chaque partie ; les salons se dissolvent après chaque partie. Ranked Play revient avec des divisions par SR et des récompenses saisonnières.', rs:['Poursuit la progression unifiée Call of Duty HQ avec Warzone.','Prestige et Battle Pass partagés entre MP, Zombies et Warzone.','Un contenu sélectionné de l\u2019ère BO6 est transféré dans l\u2019écosystème partagé.'], roadmap:[{q:'LANCEMENT',item:'Saison 1 en direct : cartes de lancement, armes et pré-saison Ranked Play.'},{q:'MI-SAISON',item:'Les drops Reloaded ajoutent des cartes, armes, événements et contenu Zombies.'},{q:'EN COURS',item:'Intégration Warzone continue et cadence saisonnière du Battle Pass.'}] },
    mw4:{ highlights:['Pas encore de notes officielles — cet opus n\u2019est pas confirmé.','Devrait poursuivre la progression unifiée Call of Duty HQ.','Section provisoire — sera complétée dès qu\u2019Activision annoncera les détails.'], matchmaking:'Devrait utiliser un matchmaking basé sur le skill cohérent avec les titres récents (skill + connexion + performances récentes, salons dissous à chaque partie). Non confirmé.', tiers:[{req:'En attente de la révélation',reward:'Structure de rang et de prestige pas encore annoncée.'}], rs:['Devrait se lier à Warzone via Call of Duty HQ.','Prise en charge du Carry-Forward non confirmée jusqu\u2019à la révélation.'], roadmap:[{q:'NON CONFIRMÉ',item:'Aucune annonce officielle. Ceci est un espace réservé pour le prochain opus attendu par la communauté.'}] },
  },
};

const IT = {
  pv: { finalTitle:'ULTIMO AGGIORNAMENTO DEL TITOLO', finalSeasonal:'ULTIMO AGGIORNAMENTO STAGIONALE', currentSeason:'STAGIONE ATTUALE', launchSeason:'STAGIONE DI LANCIO', unannounced:'NON ANNUNCIATO' },
  pd: { legacy:'Build legacy', live:'Servizio live · aggiornato per stagioni', awaiting:'In attesa della rivelazione ufficiale' },
  stdReq: ['Reset al grado massimo', 'Cinque reset', 'Prestigio finale', 'Grind dopo il prestigio'],
  stdReward: ['Emblema di prestigio, biglietto da visita e nuova progressione di sblocco', 'Token di sblocco permanente per mantenere un\u2019arma/un vantaggio tra i reset', 'Slot classe bonus, icona di prestigio e accesso alla Prestige Shop', 'Biglietto da visita Dark Ops / Master ed emblema legacy'],
  statusQ:'STATO', legacyItem:'Titolo legacy — nessun ulteriore aggiornamento di contenuti previsto. I server restano online per il gioco online.',
  g: {
    bo1:{ highlights:['Ultimo bilanciamento delle armi e dell\u2019equipaggiamento MP principali.','Economia di Contracts e COD Points finalizzata per le partite a scommessa.','Manutenzione dei server dedicati e dell\u2019anti-cheat per il gioco online.'], matchmaking:'Lobby orientate alla connessione con persistenza della lobby tra le partite — era pre-SBMM. Ibrido host/dedicato; i giocatori restano insieme tra una partita e l\u2019altra.', tiers:[{req:'Reset al grado 50',reward:'Emblema di prestigio + uno sblocco permanente tramite Prestige Token'},{req:'Dieci reset',reward:'Slot Create-a-Class extra per prestigio'},{req:'Prestigio finale',reward:'Token di sblocco massimi, emblema esclusivo e biglietto Fall'},{req:'Qualsiasi prestigio',reward:'Rimborsa tutti gli sblocchi / scegli uno sblocco permanente'}], rs:['Progressione autonoma — nessun trasferimento tra titoli.','Gli sblocchi di prestigio e i COD Points restano in Black Ops (2010).'] },
    bo2:{ highlights:['Bilanciamento dell\u2019equipaggiamento Pick 10 finalizzato su tutte le classi.','Divisioni League Play e stagioni classificate chiuse.','Regolazione delle serie di punti e ultimi aggiustamenti alle armi.'], matchmaking:'Matchmaking basato sulla connessione con divisioni League Play classificate opzionali (Bronzo → Maestro). Le playlist casual danno priorità alla connessione.', rs:['Progressione autonoma — sblocchi limitati a Black Ops II.','Prestige Master sblocca tutti gli oggetti in modo permanente in questo titolo.'] },
    bo3:{ highlights:['Bilanciamento delle abilità degli specialisti e delle armi finalizzato.','Cosmetici Black Market / supply drop completamente sbloccati in rotazione.','Integrazione e correzioni del pacchetto mappe Zombies Chronicles.'], matchmaking:'Matchmaking influenzato dall\u2019abilità con stagioni classificate Arena. Le playlist standard pesano connessione e prestazioni recenti.', rs:['Progressione autonoma — nessun collegamento HQ/Warzone (prima di Warzone).','Master Prestige (fino a 1000) concede biglietti e icone esclusive di prestigio.'] },
    bo4:{ highlights:['Bilanciamento degli specialisti e della cura manuale finalizzato.','Regolazione della mappa e dei veicoli della battle royale Blackout chiusa.','Ricompense a livelli di Black Market Contraband completamente inserite.'], matchmaking:'Matchmaking basato sull\u2019abilità in MP e Blackout, pesando prestazioni recenti e connessione; le lobby si sciolgono dopo ogni partita.', rs:['Progressione autonoma — Blackout, MP e Zombies condividono un livello account.','I livelli Contraband/Black Market sbloccano cosmetici a stagioni.'] },
    mw2019:{ highlights:['Bilanciamento Gunsmith e armi finalizzato su tutte le piattaforme.','Integrazione di Warzone (Verdansk) e regolazione dell\u2019equipaggiamento chiuse.','Ricompense stagionali del grado Ufficiale completamente ruotate.'], matchmaking:'Matchmaking basato sull\u2019abilità che combina abilità, connessione e risultati recenti per partita. Le lobby si sciolgono a ogni gioco (nessuna persistenza).', tiers:[{req:'Limite base',reward:'Sblocca Prestigio e progressione stagionale da Ufficiale'},{req:'Dopo il 55, per stagione',reward:'Livelli Battle Pass, armi e cosmetici Warzone'},{req:'Grind stagionale',reward:'Emblemi, biglietti e ciondoli d\u2019arma esclusivi della stagione'},{req:'Massimo stagionale',reward:'Migliore ricompensa stagionale + icona di prestigio'}], rs:['Progressione condivisa con il Warzone originale (era Verdansk).','Sblocchi/progetti utilizzabili nel Warzone originale; non collegati ai titoli HQ successivi.'] },
    cw:{ highlights:['Bilanciamento delle armi tra i giochi con Warzone finalizzato.','Ricompense Prestige Master stagionale (fino al livello 1000) completamente ruotate.','Zombies Outbreak e regolazione a ondate chiuse.'], matchmaking:'Matchmaking basato sull\u2019abilità che pesa abilità, connessione e prestazioni recenti; le lobby si sciolgono a ogni partita. Reset di prestigio stagionale in stile classificato.', tiers:[{req:'Reset a 55',reward:'Emblema di prestigio + reset della progressione stagionale'},{req:'Stagionale',reward:'Icona esclusiva della stagione; mantiene il livello di prestigio stagionale'},{req:'Dopo tutti i prestigi',reward:'Accesso ai livelli Master 1–1000'},{req:'Grind stagionale',reward:'Biglietto Prestige Master e icona permanente'}], rs:['Livello, Battle Pass e armi condivisi con Warzone (era 2020–2021) tramite un limite unificato.','Progetti e Operatori ottenuti qui utilizzabili in Warzone.'] },
    mw2:{ highlights:['Progressione di piattaforma d\u2019arma / ricevitore finalizzata.','Regolazione dell\u2019integrazione di Warzone 2.0 e DMZ chiusa.','Gradi di prestigio stagionale (fino a 250 per stagione) completamente ruotati.'], matchmaking:'Matchmaking basato sull\u2019abilità in MP e Warzone, combinando abilità, connessione e prestazioni recenti; le lobby si sciolgono a ogni partita.', tiers:[{req:'Limite base',reward:'Sblocca la progressione di prestigio stagionale'},{req:'Per stagione',reward:'Icone di prestigio stagionale ai livelli 50/100/150/200/250'},{req:'Massimo stagionale',reward:'Progetto d\u2019arma ed emblema esclusivi della stagione'},{req:'Per stagione',reward:'Armi, Operatori e cosmetici Warzone tramite HQ'}], rs:['Base di Call of Duty HQ — progressione condivisa con Warzone 2.0.','Piattaforme d\u2019arma e ricevitori condivisi; contenuti trasferiti in MWIII.'] },
    mw3:{ highlights:['Carry-Forward di armi, Operatori e bundle di MWII finalizzato.','Livelli e missioni di Modern Warfare Zombies (MWZ) chiusi.','Ricompense Prestige Master stagionale (fino a 1000) completamente ruotate.'], matchmaking:'Matchmaking basato sull\u2019abilità che combina abilità, connessione e prestazioni recenti in MP, Warzone e MWZ; le lobby si sciolgono a ogni partita.', tiers:[{req:'Reset a 55',reward:'Emblema di prestigio + reset stagionale'},{req:'Per stagione',reward:'Icone di prestigio stagionale ogni 50 livelli'},{req:'Dopo il prestigio 10',reward:'Livelli Master 1–1000'},{req:'Grind stagionale',reward:'Biglietto Prestige Master e icona'}], rs:['Carry-Forward: tutte le armi, gli Operatori e i progetti di MWII vengono trasferiti.','Progressione e Battle Pass unificati con Warzone e MWZ tramite HQ.'] },
    bo6:{ highlights:['Regolazione dell\u2019Omnimovement: bilanciamento sprint-scivolata-tuffo e passaggio sul rinculo.','Aggiunte di armi stagionali e aggiustamenti di bilanciamento del meta.','Rotazione di mappa Zombies, Easter egg e ricompense Prestige Master.','Integrazione Warzone: inventario condiviso e sincronizzazione del Battle Pass.'], matchmaking:'Il matchmaking basato sull\u2019abilità combina abilità, connessione e prestazioni recenti a ogni partita; le lobby si sciolgono dopo ogni gioco. Ranked Play aggiunge una scala visibile di divisioni basata su SR.', rs:['Progressione unificata con Warzone tramite Call of Duty HQ.','Carry Forward: i contenuti idonei di MWII/MWIII restano utilizzabili in Warzone (non nel MP di BO6).','Battle Pass e Prestigio condivisi tra MP di BO6, Zombies e Warzone.'], roadmap:[{q:'IN STAGIONE',item:'In corso: nuove mappe MP, armi e contenuti Zombies a ogni aggiornamento di metà/grande stagione.'},{q:'RANKED PLAY',item:'Stagioni competitive con divisioni di abilità, SR e ricompense legate al grado.'},{q:'WARZONE',item:'Integrazione continua, rotazioni di mappe Resurgence e BR legate alla stagione.'}] },
    bo7:{ highlights:['Multiplayer, Zombies e campagna live al lancio con bilanciamento del primo giorno.','Omnimovement affinato e sistema di equipaggiamento/vantaggi rinnovato.','Roadmap stagionale di mappe, armi ed eventi in corso.','Integrazione completa della progressione Call of Duty HQ e Warzone.'], matchmaking:'Il matchmaking basato sull\u2019abilità combina abilità, connessione e prestazioni recenti a ogni partita; le lobby si sciolgono dopo ogni gioco. Ranked Play torna con divisioni SR e ricompense stagionali.', rs:['Continua la progressione unificata di Call of Duty HQ con Warzone.','Prestigio e Battle Pass condivisi tra MP, Zombies e Warzone.','Contenuti selezionati dell\u2019era BO6 vengono trasferiti nell\u2019ecosistema condiviso.'], roadmap:[{q:'LANCIO',item:'Stagione 1 live: mappe di lancio, armi e pre-stagione Ranked Play.'},{q:'META STAGIONE',item:'I drop Reloaded aggiungono mappe, armi, eventi e contenuti Zombies.'},{q:'IN CORSO',item:'Integrazione Warzone continua e cadenza stagionale del Battle Pass.'}] },
    mw4:{ highlights:['Ancora nessuna nota ufficiale — questo capitolo non è confermato.','Si prevede che continui la progressione unificata di Call of Duty HQ.','Sezione segnaposto — sarà completata quando Activision annuncerà i dettagli.'], matchmaking:'Si prevede l\u2019uso di matchmaking basato sull\u2019abilità in linea con i titoli recenti (abilità + connessione + prestazioni recenti, lobby sciolte a ogni partita). Non confermato.', tiers:[{req:'In attesa della rivelazione',reward:'Struttura di grado e prestigio non ancora annunciata.'}], rs:['Si prevede il collegamento con Warzone tramite Call of Duty HQ.','Supporto Carry-Forward non confermato fino alla rivelazione.'], roadmap:[{q:'NON CONFERMATO',item:'Nessun annuncio ufficiale. Questo è un segnaposto per il prossimo capitolo atteso dalla community.'}] },
  },
};

const PT = {
  pv: { finalTitle:'ÚLTIMA ATUALIZAÇÃO DO TÍTULO', finalSeasonal:'ÚLTIMA ATUALIZAÇÃO DA TEMPORADA', currentSeason:'TEMPORADA ATUAL', launchSeason:'TEMPORADA DE LANÇAMENTO', unannounced:'NÃO ANUNCIADO' },
  pd: { legacy:'Versão legada', live:'Serviço ao vivo · atualizado por temporadas', awaiting:'Aguardando a revelação oficial' },
  stdReq: ['Reinício no rank máximo', 'Cinco reinícios', 'Prestígio final', 'Farm após o prestígio'],
  stdReward: ['Emblema de prestígio, cartão de visita e novo progresso de desbloqueio', 'Ficha de desbloqueio permanente para manter uma arma/vantagem entre reinícios', 'Slots de classe bônus, ícone de prestígio e acesso à Prestige Shop', 'Cartão de visita Dark Ops / Master e emblema legado'],
  statusQ:'STATUS', legacyItem:'Título legado — sem mais atualizações de conteúdo planejadas. Os servidores permanecem online para o jogo online.',
  g: {
    bo1:{ highlights:['Último ajuste de equilíbrio das armas e do equipamento principais do MP.','Economia de Contracts e COD Points finalizada para as partidas de aposta.','Manutenção de servidores dedicados e anti-trapaça para o jogo online.'], matchmaking:'Salas focadas na conexão com persistência de sala entre partidas — era pré-SBMM. Híbrido host/dedicado; os jogadores permanecem juntos entre partidas.', tiers:[{req:'Reinício no rank 50',reward:'Emblema de prestígio + um desbloqueio permanente via Prestige Token'},{req:'Dez reinícios',reward:'Slot extra de Create-a-Class por prestígio'},{req:'Prestígio final',reward:'Máximo de fichas de desbloqueio, emblema exclusivo e cartão Fall'},{req:'Qualquer prestígio',reward:'Reembolsar todos os desbloqueios / escolher desbloqueio permanente'}], rs:['Progresso independente — sem transferência entre títulos.','Desbloqueios de prestígio e COD Points permanecem em Black Ops (2010).'] },
    bo2:{ highlights:['Equilíbrio do equipamento Pick 10 finalizado em todas as classes.','Divisões de League Play e temporadas ranqueadas encerradas.','Ajuste de sequências de pontos e mudanças finais de armas.'], matchmaking:'Matchmaking baseado na conexão com divisões opcionais de League Play por habilidade (Bronze → Mestre). Playlists casuais priorizam a conexão.', rs:['Progresso independente — desbloqueios restritos a Black Ops II.','Prestige Master desbloqueia todos os itens permanentemente dentro deste título.'] },
    bo3:{ highlights:['Equilíbrio de habilidades de especialista e armas finalizado.','Cosméticos de Black Market / supply drop totalmente desbloqueados em rotação.','Integração e correções do pacote de mapas Zombies Chronicles.'], matchmaking:'Matchmaking influenciado pela habilidade com temporadas ranqueadas de Arena. Playlists padrão ponderam conexão e desempenho recente.', rs:['Progresso independente — sem vínculo com HQ/Warzone (antes do Warzone).','Master Prestige (até 1000) concede cartões e ícones exclusivos de prestígio.'] },
    bo4:{ highlights:['Equilíbrio de especialistas e cura manual finalizado.','Ajuste do mapa e veículos da battle royale Blackout encerrado.','Recompensas por níveis de Black Market Contraband totalmente semeadas.'], matchmaking:'Matchmaking por habilidade em MP e Blackout, ponderando desempenho recente e conexão; as salas se dissolvem após cada partida.', rs:['Progresso independente — Blackout, MP e Zombies compartilham um nível de conta.','Níveis de Contraband/Black Market desbloqueiam cosméticos por temporadas.'] },
    mw2019:{ highlights:['Equilíbrio de Gunsmith e armas finalizado em todas as plataformas.','Integração do Warzone (Verdansk) e ajuste de equipamento encerrados.','Recompensas sazonais de rank de Oficial totalmente rotacionadas.'], matchmaking:'Matchmaking por habilidade que combina habilidade, conexão e resultados recentes por partida. As salas se dissolvem a cada jogo (sem persistência).', tiers:[{req:'Limite base',reward:'Desbloqueia Prestígio e progresso sazonal de Oficial'},{req:'Após o 55, por temporada',reward:'Níveis de Battle Pass, armas e cosméticos do Warzone'},{req:'Farm sazonal',reward:'Emblemas, cartões e berloques de arma exclusivos da temporada'},{req:'Máximo sazonal',reward:'Melhor recompensa sazonal + ícone de prestígio'}], rs:['Progresso compartilhado com o Warzone original (era Verdansk).','Desbloqueios/projetos utilizáveis no Warzone original; não vinculados a títulos HQ posteriores.'] },
    cw:{ highlights:['Equilíbrio de armas entre jogos com o Warzone finalizado.','Recompensas de Prestige Master sazonal (até o nível 1000) totalmente rotacionadas.','Zombies Outbreak e ajuste por rodadas encerrados.'], matchmaking:'Matchmaking por habilidade que pondera habilidade, conexão e desempenho recente; as salas se dissolvem a cada partida. Reinícios de prestígio sazonal ao estilo ranqueado.', tiers:[{req:'Reinício no 55',reward:'Emblema de prestígio + reinício de progresso sazonal'},{req:'Sazonal',reward:'Ícone exclusivo da temporada; mantém o nível de prestígio sazonal'},{req:'Após todos os prestígios',reward:'Acesso aos níveis Master 1–1000'},{req:'Farm sazonal',reward:'Cartão de Prestige Master e ícone permanente'}], rs:['Nível, Battle Pass e armas compartilhados com o Warzone (era 2020–2021) via limite unificado.','Projetos e Operadores obtidos aqui utilizáveis no Warzone.'] },
    mw2:{ highlights:['Progresso de plataforma de arma / receptor finalizado.','Ajuste de integração do Warzone 2.0 e DMZ encerrado.','Ranks de prestígio sazonal (até 250 por temporada) totalmente rotacionados.'], matchmaking:'Matchmaking por habilidade em MP e Warzone, combinando habilidade, conexão e desempenho recente; as salas se dissolvem a cada partida.', tiers:[{req:'Limite base',reward:'Desbloqueia o progresso de prestígio sazonal'},{req:'Por temporada',reward:'Ícones de prestígio sazonal nos níveis 50/100/150/200/250'},{req:'Máximo sazonal',reward:'Projeto de arma e emblema exclusivos da temporada'},{req:'Por temporada',reward:'Armas, Operadores e cosméticos do Warzone via HQ'}], rs:['Base do Call of Duty HQ — progresso compartilhado com o Warzone 2.0.','Plataformas de arma e receptores compartilhados; conteúdo levado para MWIII.'] },
    mw3:{ highlights:['Carry-Forward de armas, Operadores e pacotes de MWII finalizado.','Níveis e missões de Modern Warfare Zombies (MWZ) encerrados.','Recompensas de Prestige Master sazonal (até 1000) totalmente rotacionadas.'], matchmaking:'Matchmaking por habilidade que combina habilidade, conexão e desempenho recente em MP, Warzone e MWZ; as salas se dissolvem a cada partida.', tiers:[{req:'Reinício no 55',reward:'Emblema de prestígio + reinício sazonal'},{req:'Por temporada',reward:'Ícones de prestígio sazonal a cada 50 níveis'},{req:'Após o prestígio 10',reward:'Níveis Master 1–1000'},{req:'Farm sazonal',reward:'Cartão de Prestige Master e ícone'}], rs:['Carry-Forward: todas as armas, Operadores e projetos de MWII são transferidos.','Progresso e Battle Pass unificados com Warzone e MWZ via HQ.'] },
    bo6:{ highlights:['Ajuste do Omnimovement: equilíbrio de sprint-deslize-mergulho e passagem de recuo.','Adições de armas sazonais e ajustes de equilíbrio do meta.','Rotação de mapa de Zombies, Easter egg e recompensas de Prestige Master.','Integração do Warzone: inventário compartilhado e sincronização do Battle Pass.'], matchmaking:'O matchmaking por habilidade combina habilidade, conexão e desempenho recente a cada partida; as salas se dissolvem após cada jogo. O Ranked Play adiciona uma escada visível de divisões por SR.', rs:['Progresso unificado com o Warzone através do Call of Duty HQ.','Carry Forward: conteúdo elegível de MWII/MWIII permanece utilizável no Warzone (não no MP de BO6).','Battle Pass e Prestígio compartilhados entre o MP de BO6, Zombies e Warzone.'], roadmap:[{q:'NA TEMPORADA',item:'Em andamento: novos mapas de MP, armas e conteúdo de Zombies a cada atualização de meia/grande temporada.'},{q:'RANKED PLAY',item:'Temporadas competitivas com divisões de habilidade, SR e recompensas por rank.'},{q:'WARZONE',item:'Integração contínua, rotações de mapas de Resurgence e BR ligadas à temporada.'}] },
    bo7:{ highlights:['Multiplayer, Zombies e campanha ao vivo no lançamento com ajuste de equilíbrio do primeiro dia.','Omnimovement refinado e sistema de equipamento/vantagens renovado.','Roadmap sazonal de mapas, armas e eventos em andamento.','Integração total do progresso do Call of Duty HQ e Warzone.'], matchmaking:'O matchmaking por habilidade combina habilidade, conexão e desempenho recente a cada partida; as salas se dissolvem após cada jogo. O Ranked Play retorna com divisões por SR e recompensas sazonais.', rs:['Continua o progresso unificado do Call of Duty HQ com o Warzone.','Prestígio e Battle Pass compartilhados entre MP, Zombies e Warzone.','Conteúdo selecionado da era BO6 é transferido para o ecossistema compartilhado.'], roadmap:[{q:'LANÇAMENTO',item:'Temporada 1 ao vivo: mapas de lançamento, armas e pré-temporada de Ranked Play.'},{q:'MEIO DA TEMPORADA',item:'Os drops Reloaded adicionam mapas, armas, eventos e conteúdo de Zombies.'},{q:'EM ANDAMENTO',item:'Integração contínua do Warzone e cadência sazonal do Battle Pass.'}] },
    mw4:{ highlights:['Ainda sem notas oficiais — esta edição não está confirmada.','Espera-se que continue o progresso unificado do Call of Duty HQ.','Seção de espaço reservado — será preenchida quando a Activision anunciar os detalhes.'], matchmaking:'Espera-se o uso de matchmaking por habilidade condizente com os títulos recentes (habilidade + conexão + desempenho recente, salas dissolvidas a cada partida). Não confirmado.', tiers:[{req:'Aguardando a revelação',reward:'Estrutura de rank e prestígio ainda não anunciada.'}], rs:['Espera-se vínculo com o Warzone via Call of Duty HQ.','Suporte a Carry-Forward não confirmado até a revelação.'], roadmap:[{q:'NÃO CONFIRMADO',item:'Sem anúncio oficial. Este é um espaço reservado para a próxima edição esperada pela comunidade.'}] },
  },
};

export const SEL = { de: build(DE), es: build(ES), fr: build(FR), it: build(IT), pt: build(PT) };
